version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - cd node_modules/jest
      - ls
      - cd ../../
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - resume.pdf
    - images/*
    - styles/*
    - dist/bundle.js
