version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm test
      - cd node_modules/jest
      - echo ls
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - resume.pdf
    - images/*
    - styles/*
    - dist/bundle.js
